yasoob/intermediatePython

- __slots__magic.rst
The text confuses classes and objects. But more importantly, the code doesn't actually compile, since `class` is a keyword.
> Correct __slots__ chapter

- targeting_python_2_3.rst
* Make `print` code work and easier to understand by actually calling print
* Fix heading that contained Markdown
* Make sure code is PEP8-compliant.
It would be nice to give ipaddress a mention as well at the bottom.
> Clarify Python 2+3 targeting chapter

- object_introspection.rst
Do not parenthesize function names needlessly, and make the example a little bit nicer to follow by removing the need to know the `bool` type.
> object introspection: More consistency

- collections.rst
> Update collections for defaultDict typo

- comprehensions.rst
The "set comprehensions" described generators as set comprehensions, which aren't the same thing. Removed reference to round brackets and generators, and added set comprehension example with braces.
> correct "set comprehensions" section

- virtual_environment.rst
The --no-site-packages is deprecated and now and the default behavior when creating a virtualenv. Changed the wording to show how to use --system-site-packages to add your systems packages to the virtualenv.
> --no-site-packages is deprecated

- lambdas.rst
We already learned about map in an earlier chapter, so this note is unnecessary and incorrect.
> Remove incorrect note about map.

- collections.rst
Explicitly iterating over the range object in the form of a list comprehension (BTW, a generator expression here would be more appropriate, and easier to read) without transforming or filtering elements is unnecessary, so the range object can be used to directly feed its values to the deque on instantiation.
> Create deque instance directly from range object.

- one_liners.rst
must cat file.json | python -m json.tool
> corrected typo in json.tools

- args_and_kwargs.rst
Code should now work on both Pythons; also removed a dead `if` (mixed up with dicts as default arguments?).
> Fix *args and **kwargs code for Python 3 and PEP 8

- coroutines.rst
In Python 3 the method `.next()` has been deprecated in favor of a built-in
`next()`.  The built-in was introduced in 2.6, and therefore, compatible with
most Python installs.
> `.next()` has been deprecated in Python 3.

- decorators.rst
In the function to wrap, we print a string. In the decorator we return a string.
Better to change them both to returning a string, since you're printing what it returns.
> fixed decorator example

- __slots__magic.rst
Added an example that shows particular memory usages of examples with and without ``__slots__`` magic.
Also fixed missing ``self`` argument from ``__init__``.
> Better example of __slots__magic.rst

- collections.rst
- coroutines.rst
In line 235, I guess the third field_names should be 'type'.
> Fix typo in collections.rst

- decorators.rst
In the code example in Section 7.6.1, there were two function calls to myfunc2(), and the first call was syntactically incorrect.
This also caused the code example to not be syntax highlighted on the website.
I fixed the error, and the code should be highlighted now.
> Fixed syntax error in Section 7.6.1

- decorators.rst
```python
class email_logit(logit):
def __init__(...):
...
super(logit, self).__init__(...)  # -> super(email_logit, self).__init__(...)
```
> Fixes #132, typo in the super() call

- README.md
I noticed `classes.rst` are missing from the README, the second commit fixes that.
Another one introduces a nesting indentation for the Table of Content in README. Not sure if the original version without the indentation was intentional or not so please feel free to decline if it was.
> Add classes.rst and nesting to README

- classes.rst
Last __getitem__ example was calling for an inexistent class and inexistend key in dictionary
> Last __getitem__ example

- classes.rst
The getitem example was calling OldClass() instead of GetTest() and the output wasn't quite right.
> Fix typos in output of getitem example

- ternary_operators.rst
Hi!
At the bottom we need to use `output` variable, not `func_output`.
Otherwise, code won't work.
Cheers!
> Wrong variable name for shorthand ternary example

- generators.rst
"wondering that why" does not sound fluid.
Also, using the word 'while' in a sentence about a `for` loop may be confusing.
> Improve wording in paragraph about StopIteration

- decorators.rst
'Nesting a Decorator Within a Function' code does not ever actually call the func,
so this commit adds execution and returns the wrapped function result when tagged with decorator.
> Add func call to Nesting a Decorator Within a Function

- context_managers.rst
In the original example, if an exception occurs in the block, the generator (1) re-raises this exception (2) exits without executing the codes after "yield". In other words, the codes after "yield" are not equivalent to the "__exit__" method.
The official doc suggests we use try...finally... to mimic the behavior of "__exit__":  https://docs.python.org/3/library/contextlib.html#contextlib.contextmanager
> Fix the contextmanager example
