yasoob/intermediatePython

- exceptions.rst
* Make sure to follow PEP8 everywhere
* Be consistent about the type of string literal quotes (I suggest to write a script or otherwise make sure that you always use the same)
* Do [not use bare excepts](https://docs.python.org/2/howto/doanddont.html#except)
> Exceptions: PEP8, typos, and more

- one_liners.rst
Make sure to follow PEP8 everywhere.
> one_liners: PEP8 and text syntax

- lambdas.rst
> lambdas: follow PEP8

- comprehensions.rst
* Slightly change wording to make it a little easier to understand
* Follow PEP8
> comprehensions: Elucidate and PEP8

- enumerate.rst
> enumerate: Follow PEP8

- global_&_return.rst
> global&return: PEP8

- decorators.rst
Be more consistent about prints
> decorators: PEP8 and print as a function

- map_&_filter.rst
> map&filter: PEP8

- generators.rst
xrange is 2.x only, range works in both 2.x and 3.x
> generators: Use range instead of xrange

- debugging.rst
> debugging: typo

- collections.rst
Example missing. Did you mean something like this?
> Namedtuple to dictionary

- map_&_filter.rst
> fix spelling error

- collections.rst
- context_managers.rst
- decorators.rst
- for_-_else.rst
Fixes some missing Python formatting.
Makes the code examples look nicer.
> Fix code formatting

- classes.rst
Fix a few typos and formatting inconsistencies.
Also change "For instance" to "For example", a reader
might be confused by two different meanings of instance
close to each other in the text.
> Tidy up classes.rst

- targeting_python_2_3.rst
Some tidying, small correction and add link to official Python 2/3 porting guide.
> Fixes for Python 2/3 targeting

- one_liners.rst
Add a one liner to initialize a class and avoid a lot of boilerplate assignments
> Add one line initializer

- decorators.rst
I think this reads a little better.
> Some wording alterations and and typo fixes.

- one_liners.rst
> alternative to flatten a list

- virtual_environment.rst
> fix link in virtual_environment.rst

- decorators.rst
> Fix whitespace around can_run

- set_-_data_structure.rst
Rename it to input_set.
Fixes #36.
> Don't use input keyword as variable name

- comprehensions.rst
https://docs.python.org/2/tutorial/datastructures.html#list-comprehensions is Python 2 documentation that shows all three in action.
> Python2 supports the three types of comprehensions

- for_-_else.rst
the loop breaks if it finds a factor, and the else block catches primes, not the other way around
> make snippet and text coherent in for-else section

- collections.rst
- context_managers.rst
- coroutines.rst
- decorators.rst
- for_-_else.rst
- ternary_operators.rst
> More Py3/PEP8 compliance + documentation for enum.Enum

- decorators.rst
The output in the comments was incorrect
> a_function_requiring_decoration() - correct output

- virtual_environment.rst
> Tidy up virtual_environment.rst

- collections.rst
> fix grammar in collections.rst

- map_&_filter.rst
> map returns an iterator in python3, use list

- README.md
Minor edits. Would love to send more pull requests in the future.
> Grammar and puctuation fixes in README

- collections.rst
Syntax fixes and I also fixed the link to `enumerated type` on WIkipedia.
> Minor syntax fixes to collections text.

- comprehensions.rst
Tiny text fix and also fixed the last example as the result should have been squared (for clarity).
> Small edits to Comprehensions.

- python_c_extension.rst
Hey, I've added a chapter on the various ways to integrate C code into Python.
I hope you will find the chapter informative and to your liking.
Thanks
Deepak
> added chapter on python C extensions

- collections.rst
#38 
Let me know if the wording is correct. I'll update it according to your needs.
> fix ambiguity in namedtuple in collections.rst

- for_-_else.rst
I saw this small 't' missing and just added it . Maybe there is some other method to notify this omission but sorry I don't know about it .
> Added a 't' in for_else module at line no. 75

- exceptions.rst
thought you might want to add in this nice insight about `else` clauses in exception handling
> `else` clauses can be really nice

- map_filter.rst
It's a super useful function and always gets taught with map and filter
> Add some information on reduce! :D

- map_filter.rst
> Fixes indentation

- decorators.rst
> Capitalize Python. Minor grammar fixes

- README.md
The menu is now divided in sections with proper titles
> Restructure menu in sections

- one_liners.rst
change ``dict``s to ``dict`` s for better formatting.
> format dict to highlight on line 34 one_liners.rst

- comprehensions.rst
> fixed comparison operator. "is" to "=="

- map_filter.rst
This fixes rendering issue for map_filter pre_reduce example raised in #137
> add newline for pre-reduce code block

- virtual_environment.rst
A little bit more precise this way
> Fixes "source" command invocation example

- comprehensions.rst
Added explanation of generator comprehensions
> Updated comprehensions.rst to include generator comprehensions

- ternary_operators.rst
I'm named Ali. I struggle with body image, and have my entire life. Can we at least be nice and refer to a pet and maybe not body image issues.
> Update to be inclusive

- classes.rst
`GetTest` is the right class name.
> Fix the class name

- ternary_operators.rst
Added Short Hand ternary  @yasoob Please verify and merge, would like to keep contributing to this.
> Shorthand ternary.

- decorators.rst
Make sure the function was called.
> Make sure the function was called

- decorators.rst
> Grammar fixes

- ternary_operators.rst
Add a more common use case (in my experience) of 'None or something'
> Add additional example to ShortHand Ternary

- classes.rst
- context_managers.rst
- python_c_extension.rst
* Use "it's" for "it is"
* Use "its" for the possessive
> Grammar: Change "it's" to "its" in some places

- README.md
> Add spanish translation

- python_c_extension.rst
No stdio functions were used in this file.
> Unnecessary #include statement

- context_managers.rst
- decorators.rst
- for_-_else.rst
Correct minor underline build complaints
> Correct minor underline build complaints
